version: '2'

volumes:
  db_data: {}
  db_backups: {}

services:

  baseapp:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    command: /run_app.sh
    volumes:
      - ./data:/app/shared
    ports:
      - "3000:3000"

  mongo:
    build:
      context: .
      dockerfile: ./compose/mongo/Dockerfile
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./data:/app/shared
      - ./private/migrations:/app/migrations
      - db_data:/data/db
      - db_backups:/data/backups
    ports:
      - "27017:27017"
