version: '2'

volumes:
  db_data: {}
  db_backups: {}

services:

  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    command: /run_app.sh
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo
    env_file: .env

  mongo:
    build:
      context: .
      dockerfile: ./compose/mongo/Dockerfile
    command:
      - --storageEngine=wiredTiger
    volumes:
      - db_data:/data/db
      - db_backups:/data/backups
    ports:
      - "27017:27017"
