version: '2'

volumes:
  db_data: {}
  db_backups: {}

services:

  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
      args:
        - settings_file
    command: /run_app.sh
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    env_file: .env

  mongo:
    build:
      context: .
      dockerfile: ./compose/mongo/Dockerfile
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./data:/app/data
      - ./src/private/migrations:/app/migrations
      - db_data:/data/db
      - db_backups:/data/backups
    ports:
      - "27017:27017"
