version: '2'

volumes:
  db_data: {}
  postgres_backup: {}

services:

  meteor:
    restart: always
    build:
      context: .
      dockerfile: ./compose/meteor/Dockerfile
    command: /run_app.sh
    env_file: .env

  mongo:
    restart: always
    build: ./compose/mongo
    command:
      - --storageEngine=wiredTiger
    volumes:
      - postgres_backup:/data/backups
      - ./src/private/migrations:/app/migrations
      - db_data:/data/db

  nginx:
    restart: always
    build: ./compose/nginx
    depends_on:
      - meteor
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./public:/app/public
