version: '2'

volumes:
  db_data: {}
  db_backups: {}

services:

  meteor:
    restart: always
    build:
      context: .
      dockerfile: ./compose/meteor/Dockerfile
    command: /run_app.sh
    env_file: .env

  mongo:
    restart: always
    build: ./compose/mongo
    command:
      - --storageEngine=wiredTiger
    volumes:
      - db_backups:/data/backups
      - db_data:/data/db
      - ./src/private/migrations:/app/migrations

  nginx:
    restart: always
    build: ./compose/nginx
    depends_on:
      - meteor
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/app/public
